packages:
  - ./
  - ./bench
  - ./bench/frameworks/*

catalog:
  '@types/bun': ^1.3.6
  '@types/node': ^25.0.10
  '@typescript/native-preview': 7.0.0-dev.20260123.3
  playwright: ^1.58.0
  typescript: ^5.9.3
  vite: 8.0.0-beta.9

onlyBuiltDependencies:
  - esbuild
