import * as Lucide from 'lucide-static'
import fs from 'node:fs'
import path from 'node:path'

const OUT_FILE = path.resolve(__dirname, '../lucide-vani.ts')

const HEADER = `// ⚠️ AUTO-GENERATED FILE — DO NOT EDIT
// Generated by src/ecosystem/scripts/generate-lucide-vani.ts

import { classNames, component, renderSvgString, type SvgProps } from '@/vani'
import * as Lucide from 'lucide-static'

const svgIcon = (svg: string): ReturnType<typeof component<SvgProps>> =>
  component<SvgProps>(
    ({ className, ref, ...props }) =>
      () =>
        renderSvgString(svg, {
          className: classNames(className),
          attributes: { 'aria-hidden': 'true', ...props },
        }),
  )

`

function isValidIdentifier(name: string) {
  if (name === 'default') return false
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name)
}

function generate() {
  const iconNames = Object.keys(Lucide).sort()

  const exports = iconNames
    .filter(isValidIdentifier)
    .map((name) => `export const ${name}Icon = svgIcon(Lucide.${name})`)
    .join('\n')

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true })
  fs.writeFileSync(OUT_FILE, HEADER + exports + '\n')

  console.log(`✔ Generated ${iconNames.length} Lucide icons`)
}

generate()
